//define all the options for profile definitions here

disciplines = 	[ 	'Agriculture',
					'Anthropology',
					'Archaeology',
					'Biology',
					'Botany',
					'Chemistry',
					'Cognitive Science',
					'Earth, Ocean & Atmospheric Science',
					'Ecology',
					'Engineering',
					'Forensics',
					'Kinesiology',
					'Microbiology & Immunology',
					'Nanotechnology',
					'Neuroscience',
					'Palaentology',
					'Pharmacology',
					'Physics & Astronomy',
					'Statistics & Math',
					'Zoology',
					'Any Discipline'
				],

languages = [ 	'BASIC',
				'C / C++',
				'C#',
				'Clojure',
				'CSS',
				'Erlang',
				'Fortran',
				'Go',
				'Haskell',
				'HTML',
				'Java',
				'JavaScript',
				'LabView',
				'Lisp',
				'MATLAB',
				'Objective C',
				'Perl',
				'PHP',
				'Python',
				'R',
				'Ruby',
				'Rust',
				'SQL',
				'Tcl',
				'Verilog',
				'VHDL',
				'Any Language'
			],

affiliations = ['Academic Lab',
				'Government Lab',
				'Private Lab (For Profit)',
				'Private Lab (Nonprofit)',
				'Independent / Other'
			];